migrate: 
	sea-orm-cli migrate -d migrations 
force-migrate:
	sea-orm-cli migrate -d migrations fresh
new-migration NAME:
  sea-orm-cli migrate -d migrations generate {{NAME}}

# Generate models with custom code preserved in separate dto module
gen-models:
	rm ./models/src/*.rs || true
	sea-orm-cli generate entity -l --model-extra-attributes 'serde(crate="rocket::serde")' --with-serde both --with-copy-enums -o  ./models/src
	./scripts/fix_serde_imports.sh ./models/src
	# Restore the dto module which is not generated by sea-orm
	git checkout HEAD -- ./models/src/dto.rs || echo "Warning: dto.rs not found in git, keeping current version"
	echo "✅ Models generated with fixed serde imports and preserved DTO module"

# Generate models with basic serde import fixing only (legacy)
gen-models-simple:
	rm ./models/src/*.rs || true
	sea-orm-cli generate entity -l --model-extra-attributes 'serde(crate="rocket::serde")' --with-serde both --with-copy-enums -o  ./models/src
	./scripts/fix_serde_imports.sh ./models/src
	git checkout HEAD -- ./models/src/dto.rs || echo "Warning: dto.rs not found in git, keeping current version"
	echo "✅ Models generated with fixed serde imports and preserved DTO module"

