[default]
limits.file = "1 GB"
limits.data-form = "1 GB"
limits.form = "1 GB"
data_path = "/home/tod/.local/share/blog"

[default.databases.sea_orm]
url = "sqlite:///tmp/rocket_blog.db?mode=rwc"

[debug.databases.sea_orm]
url = "sqlite:///tmp/rocket_blog.db?mode=rwc"

[release]
secret_key = "IbP06YnohvhdpzC/dHzUci4zUEL44Gl54fouYYvTxMg="
data_path = "/app/data"
