[default]
limits.file = "1 GB"
limits.data-form = "1 GB"
limits.form = "1 GB"
data_path = "/home/tod/.local/share/blog"

[default.databases.sea_orm]
# PostgreSQL connection string
url = "postgres://master:password@localhost/tdavis_dev"
# Or SQLite connection string (uncomment to use SQLite instead):
# url = "sqlite:blog.db?mode=rwc"

[release]
secret_key = "IbP06YnohvhdpzC/dHzUci4zUEL44Gl54fouYYvTxMg="
data_path = "/app/data"
