[default]
limits.file = "1 GB"
limits.data-form = "1 GB"
limits.form = "1 GB"
data_path = "/home/tod/.local/share/blog"
template_dir = "../../templates"

[default.databases.sea_orm]
url = "postgres://master:password@localhost/tdavis_dev"

[release]
secret_key = "IbP06YnohvhdpzC/dHzUci4zUEL44Gl54fouYYvTxMg="
data_path = "/app/data"
