//! `SeaORM` Entity. Generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "work_role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub hourly_rate: Decimal,
    pub is_active: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::work_session::Entity")]
    WorkSession,
}

impl Related<super::work_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}