//! `SeaORM` Entity. Generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "work_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub account_id: Uuid,
    pub work_role_id: Uuid,
    pub clock_in_time: DateTime,
    #[sea_orm(nullable)]
    pub clock_out_time: Option<DateTime>,
    #[sea_orm(nullable)]
    pub duration_minutes: Option<i32>,
    #[sea_orm(nullable)]
    pub earnings: Option<Decimal>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Account,
    #[sea_orm(
        belongs_to = "super::work_role::Entity",
        from = "Column::WorkRoleId",
        to = "super::work_role::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    WorkRole,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::work_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}