//! # Query Builder Usage Examples
//!
//! This module demonstrates practical usage of the CodeIgniter3-style query builder
//! generated by the `#[derive(QueryBuilder)]` proc macro. Each example showcases
//! different aspects of the API and common query patterns.
//!
//! ## Key Features Demonstrated
//!
//! - **Type-safe queries**: All column references use the entity's `Column` enum
//! - **Fluent interface**: Method chaining for readable query construction
//! - **Multiple conditions**: Combining WHERE clauses with different operators
//! - **Sorting and pagination**: ORDER BY, LIMIT, and OFFSET support
//! - **Execution methods**: `get()`, `first()`, and `count()` for different use cases
//!
//! ## Usage Pattern
//!
//! All examples follow the same pattern:
//! 1. Start with `Entity::query()` to create a new builder
//! 2. Chain filtering methods like `where_eq()`, `like()`, etc.
//! 3. Add sorting with `order_asc()` or `order_desc()`
//! 4. Apply pagination with `limit()` and/or `offset()`
//! 5. Execute with `get()`, `first()`, or `count()`

use models::{post, post::ModelQueryBuilder};
use sea_orm::{DbConn, Order};

/// Example demonstrating the CodeIgniter3-style query builder
/// This showcases how to use the generated query builder for Sea-ORM entities
pub struct QueryBuilderExample;

impl QueryBuilderExample {
    /// Example: Basic query with WHERE condition
    pub async fn find_published_posts(db: &DbConn) -> Result<Vec<post::Model>, sea_orm::DbErr> {
        post::Entity::query()
            .where_eq(post::Column::Draft, false)
            .order_desc(post::Column::DatePublished)
            .limit(10)
            .get(db)
            .await
    }

    /// Example: Search posts by title pattern
    pub async fn search_posts_by_title(
        db: &DbConn,
        search_term: &str,
    ) -> Result<Vec<post::Model>, sea_orm::DbErr> {
        post::Entity::query()
            .like(post::Column::Title, search_term)
            .where_eq(post::Column::Draft, false)
            .order_asc(post::Column::Title)
            .get(db)
            .await
    }

    /// Example: Get first post by specific author
    pub async fn get_first_post_by_author(
        db: &DbConn,
        author_id: uuid::Uuid,
    ) -> Result<Option<post::Model>, sea_orm::DbErr> {
        post::Entity::query()
            .where_eq(post::Column::AccountId, author_id)
            .where_eq(post::Column::Draft, false)
            .order_desc(post::Column::DatePublished)
            .first(db)
            .await
    }

    /// Example: Count posts with specific conditions
    pub async fn count_draft_posts(db: &DbConn) -> Result<u64, sea_orm::DbErr> {
        post::Entity::query()
            .where_eq(post::Column::Draft, true)
            .count(db)
            .await
    }

    /// Example: Complex query with multiple conditions
    pub async fn find_recent_posts_with_excerpt(
        db: &DbConn,
        limit: u64,
        offset: u64,
    ) -> Result<Vec<post::Model>, sea_orm::DbErr> {
        post::Entity::query()
            .where_eq(post::Column::Draft, false)
            .where_not_null(post::Column::Excerpt)
            .order_desc(post::Column::DatePublished)
            .limit(limit)
            .offset(offset)
            .get(db)
            .await
    }

    /// Example: Find posts by multiple IDs
    pub async fn find_posts_by_ids(
        db: &DbConn,
        post_ids: Vec<uuid::Uuid>,
    ) -> Result<Vec<post::Model>, sea_orm::DbErr> {
        post::Entity::query()
            .where_in(post::Column::Id, post_ids)
            .order_desc(post::Column::DatePublished)
            .get(db)
            .await
    }

    /// Example: OR condition query
    pub async fn find_posts_by_title_or_excerpt(
        db: &DbConn,
        search_term: &str,
    ) -> Result<Vec<post::Model>, sea_orm::DbErr> {
        // Note: This demonstrates the OR functionality
        // In a real implementation, you might want a more sophisticated OR builder
        post::Entity::query()
            .like(post::Column::Title, search_term)
            .or_where_eq(post::Column::Draft, false) // This would need enhancement for proper OR with LIKE
            .get(db)
            .await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sea_orm::{ConnectionTrait, Database, MockDatabase, MockExecResult, DbBackend};

    #[tokio::test]
    async fn test_query_builder_basic() {
        // Create a mock database for testing
        let db = MockDatabase::new(DbBackend::Postgres)
            .append_query_results([
                vec![post::Model {
                    id: uuid::Uuid::new_v4(),
                    seq_id: 1,
                    title: "Test Post".to_string(),
                    text: "Test content".to_string(),
                    excerpt: Some("Test excerpt".to_string()),
                    path: Some("/test-post".to_string()),
                    draft: Some(false),
                    date_published: chrono::Utc::now().naive_utc(),
                    account_id: uuid::Uuid::new_v4(),
                }]
            ])
            .into_connection();

        // Test the query builder
        let posts = QueryBuilderExample::find_published_posts(&db).await;
        assert!(posts.is_ok());
        
        let posts = posts.unwrap();
        assert_eq!(posts.len(), 1);
        assert_eq!(posts[0].title, "Test Post");
    }

    #[tokio::test]
    async fn test_query_builder_search() {
        let db = MockDatabase::new(DbBackend::Postgres)
            .append_query_results([
                vec![post::Model {
                    id: uuid::Uuid::new_v4(),
                    seq_id: 1,
                    title: "Searchable Post".to_string(),
                    text: "Test content".to_string(),
                    excerpt: Some("Test excerpt".to_string()),
                    path: Some("/searchable-post".to_string()),
                    draft: Some(false),
                    date_published: chrono::Utc::now().naive_utc(),
                    account_id: uuid::Uuid::new_v4(),
                }]
            ])
            .into_connection();

        let posts = QueryBuilderExample::search_posts_by_title(&db, "search").await;
        assert!(posts.is_ok());
        
        let posts = posts.unwrap();
        assert_eq!(posts.len(), 1);
        assert!(posts[0].title.contains("Searchable"));
    }

    #[tokio::test]
    async fn test_query_builder_count() {
        let db = MockDatabase::new(DbBackend::Postgres)
            .append_query_results([
                vec![post::Model {
                    id: uuid::Uuid::new_v4(),
                    seq_id: 1,
                    title: "Draft Post".to_string(),
                    text: "Test content".to_string(),
                    excerpt: Some("Test excerpt".to_string()),
                    path: Some("/draft-post".to_string()),
                    draft: Some(true),
                    date_published: chrono::Utc::now().naive_utc(),
                    account_id: uuid::Uuid::new_v4(),
                }]
            ])
            .into_connection();

        let count = QueryBuilderExample::count_draft_posts(&db).await;
        assert!(count.is_ok());
    }
}