//! User account entity and related structures.
//!
//! This module defines the account model for user authentication and management.
//! Generated by SeaORM with manual additions for form handling and API integration.

use sea_orm::entity::prelude::*;
// manual addition
use rocket::serde::{Deserialize, Serialize};
use sea_orm::{DerivePartialModel, FromQueryResult};
use rocket::FromForm;
// end manual addition

/// User account model representing registered users.
///
/// This entity stores user authentication and profile information including:
/// - Unique UUID-based identification  
/// - Username and email for login
/// - Hashed password for security
/// - Admin privilege flag
///
/// The model is serializable for API responses and integrates with
/// Rocket's form handling system.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "account")]
#[serde(crate = "rocket::serde")]
pub struct Model {
    /// Unique UUID identifier for the account
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// Username for login (must be unique)
    pub username: String,
    /// Email address for the account
    pub email: String,
    /// Bcrypt-hashed password
    pub password: String,
    /// Whether the user has administrative privileges
    pub admin: bool,
}

/// Form DTO for user login requests.
/// 
/// This structure captures username and password from login forms,
/// providing validation and seamless integration with Rocket's form handling.
/// 
/// # Security Note
/// 
/// Passwords are handled in plain text in this DTO but are immediately
/// hashed using bcrypt before storage or comparison.
#[derive(
    Clone,
    Debug,
    PartialEq,
    DerivePartialModel,
    FromQueryResult,
    Eq,
    Serialize,
    Deserialize,
    FromForm,
)]
#[serde(crate = "rocket::serde")]
#[sea_orm(entity = "Entity")]
pub struct FormDTO {
    /// Username for authentication
    pub username: String,
    /// Plain text password (hashed before storage)
    pub password: String,
}
/// end manual addition
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::post::Entity")]
    Post,
}

impl Related<super::post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Post.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
