//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use rocket::serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;
use query_builder_macro::QueryBuilder;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, QueryBuilder)]
#[sea_orm(table_name = "comment")]
#[serde(crate = "rocket::serde")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub post_id: Uuid,
    pub text: String,
    pub date_published: DateTime,
    pub user_id: Option<Uuid>,
    pub username: Option<String>,
    pub parent_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::UserId", 
        to = "super::account::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Account,
    #[sea_orm(
        belongs_to = "super::post::Entity",
        from = "Column::PostId",
        to = "super::post::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Post,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Post.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
