//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

// manual addition
use rocket::serde::{Deserialize, Serialize};
use sea_orm::DerivePartialModel;
use sea_orm::FromQueryResult;
use rocket::FromForm;
// end manual addition
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "post")]
#[serde(crate = "rocket::serde")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub seq_id: i32,
    pub title: String,
    pub text: String,
    pub path: Option<String>,
    pub draft: Option<bool>,
    pub date_published: DateTime,
    pub account_id: Uuid,
}
// Manual addition
#[derive(
    Clone, Debug, PartialEq, Eq, DerivePartialModel, FromQueryResult, Serialize, Deserialize,
)]
#[serde(crate = "rocket::serde")]
#[sea_orm(entity = "Entity")]
pub struct TitleResult {
    pub id: Uuid,
    pub seq_id: i32,
    pub title: String,
}
// end Manual addition

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Account,
    #[sea_orm(has_many = "super::comment::Entity")]
    Comment,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
