//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::account::Entity as Account;
pub use super::comment::Entity as Comment;
pub use super::event::Entity as Event;
pub use super::post::Entity as Post;
pub use super::post_tag::Entity as PostTag;
pub use super::tag::Entity as Tag;
